version: "3"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    ports:
      - "3316:3306"
    environment:
          MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
